from __future__ import annotations

from datetime import datetime
from typing import Any, Dict

from .base_formatter import BaseFormatter

_STYLES = {
    "body": (
        "margin:0;padding:0;background:#f4f4f4;font-family:Georgia,serif;"
        "font-size:15px;color:#222;"
    ),
    "wrapper": (
        "max-width:680px;margin:0 auto;background:#ffffff;"
        "border:1px solid #ddd;"
    ),
    "header": (
        "background:#1a1a2e;color:#ffffff;padding:28px 32px;"
        "text-align:center;"
    ),
    "header_title": "margin:0;font-size:26px;font-weight:bold;letter-spacing:1px;",
    "header_sub": "margin:8px 0 0;font-size:13px;color:#aaa;",
    "section": "padding:0 32px 24px;",
    "section_heading": (
        "margin:28px 0 12px;padding-bottom:6px;font-size:19px;font-weight:bold;"
        "color:#1a1a2e;border-bottom:2px solid #1a1a2e;text-transform:uppercase;"
        "letter-spacing:0.5px;"
    ),
    "subsection_heading": (
        "margin:20px 0 8px;font-size:14px;font-weight:bold;color:#555;"
        "text-transform:uppercase;letter-spacing:0.5px;"
    ),
    "article": "margin-bottom:18px;padding-bottom:18px;border-bottom:1px solid #eee;",
    "article_title": "margin:0 0 4px;font-size:16px;font-weight:bold;",
    "article_link": "color:#0056b3;text-decoration:none;",
    "article_meta": "margin:0 0 6px;font-size:12px;color:#888;",
    "article_summary": "margin:0;font-size:14px;color:#444;line-height:1.5;",
    "footer": (
        "background:#f4f4f4;padding:16px 32px;text-align:center;"
        "font-size:12px;color:#999;border-top:1px solid #ddd;"
    ),
    "error_box": (
        "margin:16px 0;padding:12px 16px;background:#fff3f3;"
        "border-left:4px solid #cc0000;font-size:13px;color:#cc0000;"
    ),
}


class EmailFormatter(BaseFormatter):
    """Formats curated news data as an HTML email."""

    def format(self, data: Dict[str, Any]) -> str:
        overall_meta = data.get("_metadata", {})
        generation_time = overall_meta.get("generation_timestamp", "")

        try:
            dt = datetime.fromisoformat(generation_time)
            display_time = dt.strftime("%B %-d, %Y")
        except (ValueError, TypeError):
            display_time = generation_time or ""

        subject_date = f" — {display_time}" if display_time else ""
        sections_html = self._render_sections(data)
        errors_html = self._render_errors(overall_meta.get("errors", []))

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Daily News Digest{subject_date}</title>
</head>
<body style="{_STYLES['body']}">
<div style="{_STYLES['wrapper']}">
  <div style="{_STYLES['header']}">
    <h1 style="{_STYLES['header_title']}">Daily News Digest</h1>
    {f'<p style="{_STYLES["header_sub"]}">{display_time}</p>' if display_time else ''}
  </div>
  <div style="{_STYLES['section']}">
    {sections_html}
    {errors_html}
  </div>
  <div style="{_STYLES['footer']}">
    Generated by kagi-curator
  </div>
</div>
</body>
</html>"""

    def _render_sections(self, data: Dict[str, Any]) -> str:
        parts: list[str] = []
        for key, section in data.items():
            if key == "_metadata" or not isinstance(section, dict):
                continue
            section_name = section.get("_metadata", {}).get("section_name", key)
            subsections_html = self._render_subsections(section)
            parts.append(
                f'<h2 style="{_STYLES["section_heading"]}">{_esc(section_name)}</h2>'
                f"{subsections_html}"
            )
        return "\n".join(parts)

    def _render_subsections(self, section: Dict[str, Any]) -> str:
        parts: list[str] = []
        for key, subsection in section.items():
            if key == "_metadata" or not isinstance(subsection, dict):
                continue
            articles = subsection.get("articles", [])
            articles_html = self._render_articles(articles) if articles else (
                f'<p style="color:#888;font-size:13px;">No articles found.</p>'
            )
            parts.append(
                f'<h3 style="{_STYLES["subsection_heading"]}">{_esc(key)}</h3>'
                f"{articles_html}"
            )
        return "\n".join(parts)

    def _render_articles(self, articles: list) -> str:
        parts: list[str] = []
        for article in articles:
            title = article.get("title") or "No title"
            url = article.get("url") or ""
            source = article.get("source") or ""
            summary = article.get("summary") or ""
            published = article.get("published_date") or ""

            meta_parts = []
            if source:
                meta_parts.append(_esc(source))
            if published:
                try:
                    dt = datetime.fromisoformat(str(published))
                    meta_parts.append(dt.strftime("%b %-d, %Y"))
                except (ValueError, TypeError):
                    pass

            title_html = (
                f'<a href="{_esc(url)}" style="{_STYLES["article_link"]}">'
                f"{_esc(title)}</a>"
                if url else _esc(title)
            )
            meta_html = (
                f'<p style="{_STYLES["article_meta"]}">{" · ".join(meta_parts)}</p>'
                if meta_parts else ""
            )
            summary_html = (
                f'<p style="{_STYLES["article_summary"]}">{_esc(summary)}</p>'
                if summary else ""
            )
            parts.append(
                f'<div style="{_STYLES["article"]}">'
                f'<p style="{_STYLES["article_title"]}">{title_html}</p>'
                f"{meta_html}"
                f"{summary_html}"
                f"</div>"
            )
        return "\n".join(parts)

    def _render_errors(self, errors: list) -> str:
        if not errors:
            return ""
        items = "".join(f"<li>{_esc(str(e))}</li>" for e in errors)
        return (
            f'<div style="{_STYLES["error_box"]}">'
            f"<strong>Errors encountered:</strong><ul>{items}</ul>"
            f"</div>"
        )


def _esc(text: str) -> str:
    """Minimal HTML escaping for attribute and text values."""
    return (
        str(text)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )
